use_frameworks!

target 'PYTransitionAnimater_Example' do
  pod 'PYTransitionAnimater', :path => '../'

  target 'PYTransitionAnimater_Tests' do
    inherit! :search_paths

#    pod 'FBSnapshotTestCase'
  end
end
